apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskservice
spec:
  selector:
    matchLabels:
      app: taskservice
  template:
    metadata:
      labels:
        app: taskservice
    spec:
      containers:
        - name: taskservice
          image: nyeineisandarsoe/taskservice:2.0.0
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: taskservice
spec:
  type: NodePort
  selector:
    app: taskservice
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31290
